# Generated by Django 5.2.4 on 2025-07-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('best_season', models.CharField(blank=True, max_length=40)),
                ('difficulty', models.CharField(blank=True, max_length=20, null=True)),
                ('meals', models.CharField(blank=True, max_length=200, null=True)),
                ('group_size', models.CharField(blank=True, max_length=200, null=True)),
                ('trip_nature', models.CharField(blank=True, max_length=100, null=True)),
                ('accomodation', models.CharField(blank=True, max_length=100, null=True)),
                ('max_altitude', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
