# Generated by Django 5.2.4 on 2025-07-16 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_management', '0001_initial'),
        ('destination_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_management.activitymanagement'),
        ),
    ]
