# Generated by Django 5.2.4 on 2025-07-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagemanagement',
            name='destination',
        ),
    ]
