# Generated by Django 5.2.4 on 2025-07-15 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('currency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('guaranteed', 'Guaranteed'), ('limited', 'Limited'), ('full', 'Full')], default='guaranteed', max_length=20)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='destination_management.destination')),
            ],
        ),
    ]
