# Generated by Django 5.2.4 on 2025-07-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('reading_time', models.CharField(blank=True, help_text='eg:5 minutes', max_length=200, null=True)),
                ('description', models.TextField()),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='blogs/feature/')),
                ('is_popular', models.BooleanField(default=False)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
