# Generated by Django 5.2.4 on 2025-07-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='homepage/videos/')),
                ('video_link', models.URLField(blank=True, help_text='eg: YouTube/Vimeo URL', null=True)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='homepage/video_preview')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
