# Generated by Django 5.2.4 on 2025-07-16 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination_management', '0002_destination_activity'),
        ('package_management', '0002_remove_packagemanagement_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('package_type', models.CharField(blank=True, max_length=100)),
                ('activity_type', models.CharField(blank=True, max_length=100)),
                ('activities', models.TextField(blank=True)),
                ('customize_trip', models.TextField(blank=True)),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_management', to='destination_management.destination')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_management', to='package_management.packagemanagement')),
            ],
        ),
    ]
