# Generated by Django 5.2.4 on 2025-07-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package_management', '0002_remove_packagemanagement_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='activity_images/')),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('package', models.ManyToManyField(blank=True, help_text='Packages that include this activity', related_name='activities', to='package_management.packagemanagement')),
            ],
        ),
    ]
